import {
  Business,
  Property,
  AdUnit,
  Advertiser,
  Brand,
  Contact,
  Opportunity,
  Campaign,
  Flight,
  Creative,
  DeliveryFlightDaily,
} from '@/lib/types';

export const demoBusiness: Business = {
  id: 'demo-business-1',
  name: 'Kevel Demo',
  region: 'EU',
  settings_json: {},
};

export const demoProperties: Property[] = [
  {
    id: 'prop-1',
    business_id: 'demo-business-1',
    name: 'continente.pt',
    domain: 'continente.pt',
  },
  {
    id: 'prop-2',
    business_id: 'demo-business-1',
    name: 'wells.pt',
    domain: 'wells.pt',
  },
];

export const demoAdUnits: AdUnit[] = [
  {
    id: 'au-1',
    business_id: 'demo-business-1',
    property_id: 'prop-1',
    name: 'Billboard',
    iab_standard: true,
    width: 970,
    height: 250,
    external_ref: 'kevel-au-970x250',
  },
  {
    id: 'au-2',
    business_id: 'demo-business-1',
    property_id: 'prop-1',
    name: 'Leaderboard',
    iab_standard: true,
    width: 728,
    height: 90,
    external_ref: 'kevel-au-728x90',
  },
  {
    id: 'au-3',
    business_id: 'demo-business-1',
    property_id: 'prop-1',
    name: 'Medium Rectangle',
    iab_standard: true,
    width: 300,
    height: 250,
    external_ref: 'kevel-au-300x250',
  },
  {
    id: 'au-4',
    business_id: 'demo-business-1',
    property_id: 'prop-2',
    name: 'Skyscraper',
    iab_standard: true,
    width: 160,
    height: 600,
    external_ref: 'kevel-au-160x600',
  },
  {
    id: 'au-5',
    business_id: 'demo-business-1',
    property_id: 'prop-2',
    name: 'Mobile Banner',
    iab_standard: true,
    width: 320,
    height: 50,
    external_ref: 'kevel-au-320x50',
  },
];

export const demoAdvertisers: Advertiser[] = [
  {
    id: 'adv-1',
    business_id: 'demo-business-1',
    name: 'Sonae MC',
    parent_name: 'Sonae',
    sf_id: 'SF-001',
  },
  {
    id: 'adv-2',
    business_id: 'demo-business-1',
    name: 'Jerónimo Martins',
    parent_name: 'Jerónimo Martins Group',
    sf_id: 'SF-002',
  },
  {
    id: 'adv-3',
    business_id: 'demo-business-1',
    name: 'ECI',
    parent_name: 'El Corte Inglés',
    sf_id: 'SF-003',
  },
];

export const demoBrands: Brand[] = [
  {
    id: 'brand-1',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Continente',
  },
  {
    id: 'brand-2',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Bom Dia',
  },
  {
    id: 'brand-3',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'Pingo Doce',
  },
  {
    id: 'brand-4',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'Recheio',
  },
  {
    id: 'brand-5',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-3',
    name: 'El Corte Inglés',
  },
  {
    id: 'brand-6',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-3',
    name: 'Supercor',
  },
];

export const demoContacts: Contact[] = [
  {
    id: 'contact-1',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Maria Silva',
    email: 'maria.silva@unilever.com',
    title: 'Marketing Manager',
    sf_id: 'SF-C-001',
  },
  {
    id: 'contact-2',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'João Santos',
    email: 'joao.santos@pg.com',
    title: 'Brand Director',
    sf_id: 'SF-C-002',
  },
  {
    id: 'contact-3',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-3',
    name: 'Ana Costa',
    email: 'ana.costa@nestle.com',
    title: 'Digital Lead',
    sf_id: 'SF-C-003',
  },
  {
    id: 'contact-4',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Pedro Rodrigues',
    email: 'pedro.rodrigues@unilever.com',
    title: 'Media Planner',
    sf_id: 'SF-C-004',
  },
  {
    id: 'contact-5',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'Sofia Almeida',
    email: 'sofia.almeida@pg.com',
    title: 'Campaign Manager',
    sf_id: 'SF-C-005',
  },
];

export const demoOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Continente Q1 2025 Campaign',
    stage: 'Negotiation',
    amount: 85000,
    close_date: '2025-11-15',
    owner: 'Sales User',
    sf_id: 'SF-OPP-001',
  },
  {
    id: 'opp-2',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Bom Dia Brand Launch',
    stage: 'Proposal',
    amount: 45000,
    close_date: '2025-10-30',
    owner: 'Sales User',
    sf_id: 'SF-OPP-002',
  },
  {
    id: 'opp-3',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'Pingo Doce Summer Push',
    stage: 'Qualification',
    amount: 65000,
    close_date: '2025-12-01',
    owner: 'Sales User',
    sf_id: 'SF-OPP-003',
  },
  {
    id: 'opp-4',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'Recheio B2B Campaign',
    stage: 'Closed Won',
    amount: 120000,
    close_date: '2025-09-20',
    owner: 'Sales User',
  },
  {
    id: 'opp-5',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-3',
    name: 'ECI Holiday Special',
    stage: 'Prospecting',
    amount: 95000,
    close_date: '2026-01-30',
    owner: 'Sales User',
    sf_id: 'SF-OPP-005',
  },
  {
    id: 'opp-6',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-3',
    name: 'Supercor Loyalty Program',
    stage: 'Proposal',
    amount: 55000,
    close_date: '2025-11-25',
    owner: 'Sales User',
    sf_id: 'SF-OPP-006',
  },
  {
    id: 'opp-7',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    name: 'Continente Back to School',
    stage: 'Closed Lost',
    amount: 35000,
    close_date: '2025-09-15',
    owner: 'Sales User',
    sf_id: 'SF-OPP-007',
  },
  {
    id: 'opp-8',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    name: 'Pingo Doce Always-On Display',
    stage: 'Negotiation',
    amount: 150000,
    close_date: '2025-11-10',
    owner: 'Sales User',
    sf_id: 'SF-OPP-008',
  },
];

export const demoCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-1',
    property_id: 'prop-1',
    name: 'Continente Q1 2025',
    status: 'live',
    budget: 85000,
    owner: 'Ad Ops User',
    kevel_id: 'KVL-CAMP-001',
  },
  {
    id: 'camp-2',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    property_id: 'prop-2',
    name: 'Pingo Doce Spring Push',
    status: 'live',
    budget: 65000,
    owner: 'Ad Ops User',
    kevel_id: 'KVL-CAMP-002',
  },
  {
    id: 'camp-3',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-3',
    property_id: 'prop-1',
    name: 'ECI Holiday Campaign',
    status: 'ready',
    budget: 95000,
    owner: 'Ad Ops User',
  },
  {
    id: 'camp-4',
    business_id: 'demo-business-1',
    advertiser_id: 'adv-2',
    property_id: 'prop-1',
    name: 'Recheio B2B Launch',
    status: 'completed',
    budget: 120000,
    owner: 'Ad Ops User',
    kevel_id: 'KVL-CAMP-004',
  },
];

const now = new Date();
const lastWeek = new Date(now);
lastWeek.setDate(lastWeek.getDate() - 7);
const nextWeek = new Date(now);
nextWeek.setDate(nextWeek.getDate() + 7);
const nextMonth = new Date(now);
nextMonth.setMonth(nextMonth.getMonth() + 1);
const twoMonths = new Date(now);
twoMonths.setMonth(twoMonths.getMonth() + 2);

export const demoFlights: Flight[] = [
  {
    id: 'flight-1',
    campaign_id: 'camp-1',
    ad_unit_id: 'au-1',
    name: 'Continente Billboard Hero',
    start_at: lastWeek.toISOString().split('T')[0],
    end_at: nextMonth.toISOString().split('T')[0],
    always_on: false,
    pricing_model: 'CPM',
    rate: 5.5,
    goal_type: 'IMPRESSIONS',
    goal_amount: 2000000,
    priority: 'standard',
    timezone: 'Europe/Lisbon',
    kevel_id: 'KVL-FLT-001',
  },
  {
    id: 'flight-2',
    campaign_id: 'camp-1',
    ad_unit_id: 'au-3',
    name: 'Continente Always-On Rectangle',
    start_at: lastWeek.toISOString().split('T')[0],
    always_on: true,
    pricing_model: 'FLAT',
    rate: 15000,
    goal_type: 'none',
    priority: 'standard',
    timezone: 'Europe/Lisbon',
    kevel_id: 'KVL-FLT-002',
  },
  {
    id: 'flight-3',
    campaign_id: 'camp-1',
    ad_unit_id: 'au-2',
    name: 'Continente CPC Leaderboard',
    start_at: now.toISOString().split('T')[0],
    end_at: nextWeek.toISOString().split('T')[0],
    pricing_model: 'CPC',
    rate: 2.0,
    goal_type: 'CLICKS',
    goal_amount: 75000,
    always_on: false,
    priority: 'sponsorship',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-4',
    campaign_id: 'camp-2',
    ad_unit_id: 'au-4',
    name: 'Pingo Doce Skyscraper CPM',
    start_at: now.toISOString().split('T')[0],
    end_at: nextMonth.toISOString().split('T')[0],
    always_on: false,
    pricing_model: 'CPM',
    rate: 4.0,
    goal_type: 'IMPRESSIONS',
    goal_amount: 1500000,
    priority: 'standard',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-5',
    campaign_id: 'camp-2',
    ad_unit_id: 'au-5',
    name: 'Pingo Doce Mobile CPA',
    start_at: nextMonth.toISOString().split('T')[0],
    end_at: twoMonths.toISOString().split('T')[0],
    always_on: false,
    pricing_model: 'CPA',
    rate: 30.0,
    goal_type: 'CONVERSIONS',
    goal_amount: 3000,
    priority: 'standard',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-6',
    campaign_id: 'camp-2',
    ad_unit_id: 'au-3',
    name: 'Pingo Doce Flat Fee Placement',
    start_at: now.toISOString().split('T')[0],
    end_at: nextWeek.toISOString().split('T')[0],
    always_on: false,
    pricing_model: 'FLAT',
    rate: 8000,
    goal_type: 'SPEND',
    goal_amount: 8000,
    priority: 'standard',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-7',
    campaign_id: 'camp-3',
    ad_unit_id: 'au-1',
    name: 'ECI Holiday Billboard',
    start_at: nextMonth.toISOString().split('T')[0],
    end_at: twoMonths.toISOString().split('T')[0],
    always_on: false,
    pricing_model: 'CPM',
    rate: 6.0,
    goal_type: 'IMPRESSIONS',
    goal_amount: 2500000,
    priority: 'sponsorship',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-8',
    campaign_id: 'camp-3',
    ad_unit_id: 'au-2',
    name: 'ECI CPC Banner',
    start_at: nextWeek.toISOString().split('T')[0],
    end_at: nextMonth.toISOString().split('T')[0],
    always_on: false,
    pricing_model: 'CPC',
    rate: 1.8,
    goal_type: 'CLICKS',
    goal_amount: 60000,
    priority: 'standard',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-9',
    campaign_id: 'camp-4',
    ad_unit_id: 'au-3',
    name: 'Recheio Rectangle Completed',
    start_at: '2025-09-01',
    end_at: '2025-09-30',
    always_on: false,
    pricing_model: 'CPM',
    rate: 4.5,
    goal_type: 'IMPRESSIONS',
    goal_amount: 1000000,
    priority: 'standard',
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'flight-10',
    campaign_id: 'camp-4',
    ad_unit_id: 'au-5',
    name: 'Recheio Mobile Flat Fee',
    start_at: '2025-09-01',
    end_at: '2025-09-30',
    always_on: false,
    pricing_model: 'FLAT',
    rate: 12000,
    goal_type: 'none',
    priority: 'house',
    timezone: 'Europe/Lisbon',
  },
];

export const demoCreatives: Creative[] = [
  {
    id: 'creative-1',
    campaign_id: 'camp-1',
    name: 'Dove Summer Creative 970x250',
    type: 'image',
    url: 'https://placeholder.svg',
    width: 970,
    height: 250,
  },
  {
    id: 'creative-2',
    campaign_id: 'camp-2',
    name: 'Ariel Launch Banner 728x90',
    type: 'image',
    url: 'https://placeholder.svg',
    width: 728,
    height: 90,
  },
  {
    id: 'creative-3',
    campaign_id: 'camp-1',
    name: 'Dove Rectangle 300x250',
    type: 'image',
    url: 'https://placeholder.svg',
    width: 300,
    height: 250,
  },
  {
    id: 'creative-4',
    campaign_id: 'camp-2',
    name: 'Ariel Mobile 320x50',
    type: 'image',
    url: 'https://placeholder.svg',
    width: 320,
    height: 50,
  },
];

// Generate 14 days of delivery data
export const demoDeliveryData: DeliveryFlightDaily[] = [];
for (let i = 0; i < 14; i++) {
  const date = new Date(now);
  date.setDate(date.getDate() - (13 - i));
  
  // Flight 1 data (CPM, good pacing)
  demoDeliveryData.push({
    id: `delivery-1-${i + 1}`,
    flight_id: 'flight-1',
    date: date.toISOString().split('T')[0],
    imps: Math.floor(Math.random() * 80000) + 50000,
    clicks: Math.floor(Math.random() * 800) + 500,
    spend: Math.floor(Math.random() * 400) + 250,
    convs: Math.floor(Math.random() * 40) + 10,
  });

  // Flight 3 data (CPC, at-risk pacing)
  demoDeliveryData.push({
    id: `delivery-3-${i + 1}`,
    flight_id: 'flight-3',
    date: date.toISOString().split('T')[0],
    imps: Math.floor(Math.random() * 50000) + 30000,
    clicks: Math.floor(Math.random() * 500) + 200,
    spend: Math.floor(Math.random() * 300) + 150,
    convs: Math.floor(Math.random() * 20) + 5,
  });
}
